// UK lang variables

tinyMCE.addToLang('imgmanager',{
desc : 'Insert/Edit Image',
tab_advanced : 'Advanced',
tab_optional : 'Optional',
general : 'General',
title : 'Title',
preview : 'Preview',
constrain_proportions : 'Constrain proportions',
langdir : 'Language direction',
langcode : 'Language code',
long_desc : 'Long description link',
style : 'Style',
classes : 'Classes',
ltr : 'Left to right',
rtl : 'Right to left',
id : 'Id',
image_map : 'Image map',
swap_image : 'Swap image',
popup : 'Popup Image',
alt_image : 'Alternative image',
mouseover : 'for mouse over',
mouseout : 'for mouse out',
misc : 'Miscellaneous',
optional : 'Optional',
example_img : 'Appearance&nbsp;preview&nbsp;image',
missing_alt : 'Are you sure you want to continue without including an Image Description? Without  it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.',
folder_name : 'Invalid folder name. Please choose another.',
delfile_alert : 'Delete File(s)?',
delfolder_alert : 'Delete Folder?',
rename_alert : 'Renaming files or folders will break existing links. Continue?',
move_alert : 'Moving files will break existing links. Continue?',
badrename_alert : 'The name your specified is the same as that of the thumbanil directory.'
});
