/**
* @version $Id: zh_cn.js 2006-06-5 14:01:27Z stingrey $
* @package Joomla JCE
* @copyright Copyright (C) 2006 ManCan Company. All rights reserved.
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL
* This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/
// ZH_CN lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- 样式 --',
theme_code_desc : '编辑HTML源文件',
theme_code_title : 'HTML源文件编辑器',
theme_code_wordwrap : '文字包围',
theme_sub_desc : '下标',
theme_sup_desc : '上标',
theme_hr_desc : '插入水平线',
theme_removeformat_desc : '删除格式',
theme_custom1_desc : '你的自定义描述在这',
insert_image_border : '边线',
insert_image_dimensions : '尺度',
insert_image_vspace : '垂直间距',
insert_image_hspace : '水平间距',
insert_image_align : '队列',
insert_image_align_default : '-- 未设置 --',
insert_image_align_baseline : '基线',
insert_image_align_top : '顶部',
insert_image_align_middle : '居中',
insert_image_align_bottom : '底部',
insert_image_align_texttop : '文字置顶',
insert_image_align_absmiddle : '绝对居中',
insert_image_align_absbottom : '绝对底部',
insert_image_align_left : '左对齐',
insert_image_align_right : '右对齐',
theme_font_size : '-- 字号 --',
theme_fontdefault : '-- 字体 --',
theme_block : '-- 格式 --',
theme_paragraph : '段落',
theme_div : '层',
theme_address : '地址',
theme_pre : '预处理',
theme_h1 : '标题 1',
theme_h2 : '标题 2',
theme_h3 : '标题 3',
theme_h4 : '标题 4',
theme_h5 : '标题 5',
theme_h6 : '标题 6',
theme_colorpicker_title : '取色',
theme_colorpicker_apply : '应用',
theme_forecolor_desc : '选择文本颜色',
theme_backcolor_desc : '选择背景色',
theme_charmap_title : '选择自定义字符',
theme_charmap_desc : '插入自定义字符',
theme_visualaid_desc : '显示/隐藏 虚框',
insert_anchor_title : '插入/编辑 定点位置',
insert_anchor_name : '定点位置名称',
theme_anchor_desc : '插入/编辑 定点位置',
theme_insert_link_titlefield : '标题',
theme_clipboard_msg : '复制/剪切/粘贴 功能在Mozilla和Firefox浏览器中不可用。\n你需要更多关于此版本的信息吗？',
theme_path : '路径',
cut_desc : '剪切',
copy_desc : '复制',
paste_desc : '粘贴',
link_list : '链接列表',
image_list : '图片列表',
browse : '浏览',
image_props_desc : '图片工具',
newdocument_desc : '新建文档',
class_name : '类',
newdocument : '你确定要清空所有的内容吗？',
about_title : '关于 TinyMCE',
about : '关于',
license : '许可证',
plugins : '插件',
plugin : '插件',
author : '作者',
version : '版本',
loaded_plugins : '装载插件',
help : '帮助',
not_set : '-- 未设置 --',
close : '关闭',
toolbar_focus : '工具按钮快捷键 - Alt+Q, 编辑器快捷键 - Alt-Z, 元素路径快捷键 - Alt-X'
});
