/**
* @version $Id: zh_cn.js 2006-06-5 14:01:27Z stingrey $
* @package Joomla JCE
* @copyright Copyright (C) 2006 ManCan Company. All rights reserved.
* @license http://www.gnu.org/copyleft/gpl.html GNU/GPL
* This version may have been modified pursuant
* to the GNU General Public License, and as distributed it includes or
* is derivative of works licensed under the GNU General Public License or
* other free or open source software licenses.
*/
// ZH_CN lang variables

tinyMCE.addToLang('table',{
general_tab : '一般',
advanced_tab : '高级',
general_props : '一般属性',
advanced_props : '高级属性',
desc : '插入新的表格',
row_before_desc : '在上方插入行',
row_after_desc : '在下方插入行',
delete_row_desc : '删除行',
col_before_desc : '在左侧插入列',
col_after_desc : '在右侧插入列',
delete_col_desc : '删除列',
rowtype : '行在表中的位置',
title : '插入/修改 表',
width : '宽',
height : '高',
cols : '列',
rows : '行',
cellspacing : '间距',
cellpadding : '单元间距',
border : '边框',
align : '水平对齐',
align_default : '默认',
align_left : '左对齐',
align_right : '右对齐',
align_middle : '居中',
row_title : '表格行属性',
cell_title : '表格列属性',
cell_type : '单元类型',
row_desc : '表格行属性',
cell_desc : '表格单元格属性',
valign : '垂直对齐',
align_top : '居顶',
align_bottom : '居底',
props_desc : '表格属性',
bordercolor : '边框颜色',
bgcolor : '背景颜色',
merge_cells_title : '合并单元格',
split_cells_desc : '拆分单元格',
merge_cells_desc : '合并单元格',
cut_row_desc : '剪切行',
copy_row_desc : '复制行',
paste_row_before_desc : '在前面粘贴行',
paste_row_after_desc : '在后面粘贴行',
id : 'ID',
style: '样式',
langdir : '文字方向',
langcode : '语言编码',
mime : '目标协议类型',
ltr : '从左到右',
rtl : '从右到左',
bgimage : '背景图片',
summary : '摘要',
td : "数据",
th : "标题",
cell_cell : '更新当前单元格',
cell_row : '更新行中的所有单元格',
cell_all : '更新表中的所有单元格',
row_row : '更新当前行',
row_odd : '更新奇数行',
row_even : '更新偶数行',
row_all : '更新所有行',
thead : '表格头',
tbody : '表格体',
tfoot : '表格尾',
del : '删除表格',
scope : '范围',
row : '行',
col : '列',
rowgroup : '合并行',
colgroup : '合并列',
missing_scope: '你确定在没有指明这个表格的标题单元格的情况下继续吗？如果没有它，可能会使一些用户无法理解表格的内容或者是数据。'
});
